name: Continuous Deployment
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        steps:
            - name: install Python
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9
            - name: Install EB CLI using pip
              run: |
                  python -m pip install --upgrade pip
                  pip install awsebcli
            - name: Checkout repository
              uses: actions/checkout@v3
            - name: Use Node.js 18.x
              uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - name: Install dependencies
              run: npm ci
            - name: Build production
              run: npm run build
            - name: Initialize AWS Elastic Beanstalk
              run: eb init --platform node.js --region ${{ secrets.AWS_DEFAULT_REGION }} ${{secrets.APPLICATION_NAME}}
            - name: Deploy to AWS Elastic Beanstalk
              run: eb deploy ${{secrets.ENVIRONMENT_NAME}}
